### ISSUE TITLE
disabling of filamenttracking is now possible → but why is it auto-disabled?

### ISSUE THREAD

**Issue by codingcatgirl** [OllisGit/OctoPrint-PrintJobHistory#149] opened 2021-05-25 21:09 UTC
After updating to the latest version i got a message telling me to select a plugin for filament tracking. Apparently you added the feature to *disable* it in the last version. However, i feel like it shouldn't have auto-disabled itself with that update, right?

**Comment by OllisGit** [comment] 2021-05-27 21:47
Hi @codingcatgirl!

Well, the older version always selected the filamenttracker-plugin. If both installed, it selected Filamenttracker.
Now the SpoolManager is more stable, I want that the user is explicit selecting the prefered Plugin.

Now it is "auto-disabled" after you disabled the plugin and after reenabling it you must select a plugin.

There is also an other feature in my roadmap: collecting filament-infos from gcode instead of tracking plugin.

But it shouldn't be problem for the user to select a tracker, right?

**Comment by codingcatgirl** [comment] 2021-05-27 23:47
Just easy to misunderstand, i was confused because it suddenly wanted me to do that :)

**Comment by donlook** [comment] 2021-06-01 16:40
I have also noticed that the plugin selection seems to be forgotten when OctoPrint is restarted. FilamentManager is the only plugin that I have installed and I noticed the message during the restart that I should choose a plugin.

It does not seem to happen on every restart, but if I restart several times in a row, it will forget the selection.

The attached log file has a number of restarts where the setting was both remembered and forgotten.

[octoprint.zip](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/6577757/octoprint.zip)

**Comment by dualznz** [comment] 2021-06-03 10:31
1

> I have also noticed that the plugin selection seems to be forgotten when OctoPrint is restarted. FilamentManager is the only plugin that I have installed and I noticed the message during the restart that I should choose a plugin.
> 
> It does not seem to happen on every restart, but if I restart several times in a row, it will forget the selection.
> 
> The attached log file has a number of restarts where the setting was both remembered and forgotten.
> 
> [octoprint.zip](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/6577757/octoprint.zip)

I have this same issue on auto disabled when pi is restarted

**Comment by ManuelMcLure** [comment] 2021-06-13 18:33
This appears to be a race condition - the code to check for the filament manager is called before the Filament Manager plugin is completely initialized so it shows up as disabled and the setting is set to None.

**Comment by ManuelMcLure** [comment] 2021-06-13 19:02
I've entered a PR to fix this. If you want to test whether it fixes it for you, install the version from https://github.com/ManuelMcLure/OctoPrint-PrintJobHistory/archive/refs/heads/fixfmreset.zip

**Comment by donlook** [comment] 2021-06-13 20:14
@ManuelMcLure 

I installed version 1.14.1,

When I restarted OctoPrint and looked at the filament management selection in the Print Job History plugin, both radio buttons for SpoolManger and FilamentManager are disabled. I have FilamementManager installed. SpoolManager is not installed in my configuration. See the attached screen captures. It does not seem to forget the assignment.

Thanks, let me know if I can supply any more information.

![Screenshot from 2021-06-13 15-01-58](https://user-images.githubusercontent.com/17184497/121820447-6b0af280-cc58-11eb-868e-88905a775ca8.png)

![InstalledPlugins](https://user-images.githubusercontent.com/17184497/121820582-524f0c80-cc59-11eb-8e58-112207bcf971.png)

**Comment by ManuelMcLure** [comment] 2021-06-13 20:17
@donlook did you try installing from the URL I provided using the "Get More->URL" option? The default 1.14.1 that gets installed normally does not have my fix yet.

**Comment by donlook** [comment] 2021-06-13 20:19
@ManuelMcLure 
I installed from here:
https://github.com/ManuelMcLure/OctoPrint-PrintJobHistory/archive/refs/heads/fixfmreset.zip

**Comment by ManuelMcLure** [comment] 2021-06-13 20:20
@donlook I can't reproduce it - I have the same setup as you (Filament Manager installed, Spool Manager not installed) and I see the Filament Manager radio button not disabled.

**Comment by ManuelMcLure** [comment] 2021-06-13 20:23
This is probably a timing issue, which can be difficult to reproduce and fix.

**Comment by ManuelMcLure** [comment] 2021-06-13 20:29
@donlook Can you try forcing a reload with Ctrl+Shift+R and see if that fixes it?

**Comment by ManuelMcLure** [comment] 2021-06-13 20:38
@donlook could you try uninstalling and reinstalling the plugin from the same URL? I just pushed another fix that _may_ fix your issue.

**Comment by donlook** [comment] 2021-06-13 21:00
@ManuelMcLure 
Before I installed the new fix that you provided, I did a system reboot. After that, I could not reproduce the problem. What I was seeing then that was different was the "Settings Update Detected" dialog when opening the OctoPrint Settings dialog.

After that testing, I installed your newest version. The newest version does not have the "settings changed" dialog. The original problem that I saw does not appear. I have restarted OctoPrint several times and also restarted the system as well. I have also tried it with my printer powered off as well as powered on. 

The problem seems to be resolved.

![reloadsettings](https://user-images.githubusercontent.com/17184497/121821611-a5c45900-cc5f-11eb-9790-e329df199974.png)

**Comment by ManuelMcLure** [comment] 2021-06-13 21:42
Thanks for testing. Hopefully the PR gets merged soon.

**Comment by codingcatgirl** [comment] 2021-06-30 13:51
Restarted. Removed the setting again. Hm.

**Comment by codingcatgirl** [comment] 2021-06-30 13:52
(i'm still just running the latest version)

**Comment by MrSco** [comment] 2021-10-30 12:37
Any updates on this? I set the spoolmanager filament tracker in the settings but every time I reboot, the PJHM notification shows.

**Comment by Nazar78** [comment] 2021-11-07 16:33
Getting the same issue, everytime the server reboot I also see this in the log:

2021-11-08 00:31:55,224 - octoprint.plugins.PrintJobHistory - ERROR - Filamentracking is disabled, but some plugins are installed!

**Comment by OllisGit** [comment] 2021-11-13 21:03
Hi,
new release [1.15.0](https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.15.0) is available and fix this issue.

Please test and give me a feedback. 
Thx, in advance!
Olli

**Closed** 2022-02-28 02:22 UTC
Labels: type: bug, status: markedForAutoClose, status: closedByBot
